fix: aui-table sticky-column side border disappear, dialog overflow hidden
alauda/ui pull request #372
Opened 2022-08-19 02:40 UTC by yangxiaolang

#371

2022-08-19 02:45 UTC, JounQin approved these changes

2022-08-23 02:00 UTC, fengtianze commented
顺便给`auiTableScrollShadow`加个`cdkScrollable`的provider吧

2022-09-13 10:20 UTC, JounQin requested changes

2022-09-13 10:20 UTC, JounQin commented on src/table/table-scroll.directive.ts
> +    super.ngOnDestroy();
super 的一般放在前面吧，虽然这里没啥影响

2022-09-13 10:27 UTC, yangxiaolang commented on src/table/table-scroll.directive.ts
> +    super.ngOnDestroy();
👌

2022-09-13 10:34 UTC, JounQin approved these changes

2022-09-13 10:37 UTC, fengtianze approved these changes

2022-09-13 10:55 UTC, merged