feat: back top style #ASM-14132
alauda/ui pull request #489
Opened 2023-08-02 09:04 UTC by Chenoops

回到顶部样式修改

2023-08-08 09:03 UTC, JounQin requested changes

2023-08-09 08:12 UTC, JounQin requested changes

2023-08-09 08:12 UTC, JounQin commented on src/back-top/back-top.component.scss
>    cursor: pointer;
有些不再需要的样式可以移除了吧

2023-08-09 08:25 UTC, fengtianze commented on src/back-top/back-top.component.scss
> +    color: use-rgb(n-4) !important;
hover时图标颜色不变？设计稿看一下

2023-08-09 08:31 UTC, fengtianze commented
第一个demo显示不出按钮，fix一下

2023-08-10 06:41 UTC, fengtianze approved these changes

2023-08-10 06:47 UTC, merged