feat: add resizable directive
alauda/ui pull request #533
Opened 2023-12-15 08:48 UTC by igauch

2023-12-15 08:53 UTC, JounQin commented on .changeset/fifty-hounds-stare.md
> +'@alauda/ui': patch
```suggestion
'@alauda/ui': minor
```

2023-12-15 09:05 UTC, JounQin requested changes
Need more discussion about the necessary of this feature.

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> + * 使用此指令需要引入resizable.scss
怎么引入？

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> + * 因为参考线是基于absolute定位的，所以需要在预期的地方加上relative（不自动加是为了避免修改业务布局而导致使用者出现意外的异常）
默认加到table的样式里影响只有position relative吧？应该风险很小

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +  element: HTMLElement;
改用private的用private

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +        this.renderer2.setStyle(this.resizeHandle, 'opacity', 1);
用visibility或者display属性

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +    this.renderer2.listen(this.element, 'mouseover', () => {
需不需要destroy时unlisten

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +    this.zone.runOutsideAngular(() => {
这个是否outside有什么区别？

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +      this.renderer2.setStyle(this.resizeHandle, 'opacity', 1);
调用的地方这么多，封装在方法里得了

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +    const _max = this.containerElement.clientWidth - this.getOffset();
能不能通过样式设置max-width: 100%；min-width: 0; 解决

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +  private handleWidth(width: string | number) {
复杂了，通过样式设置最大最小宽度，拖拽只改width就可以了

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +      this.mouseUpSubscription = undefined;
this.mouseUpSubscription?.unsubscribe();  this.mouseUpSubscription = null;

2023-12-15 09:48 UTC, fengtianze commented on src/table/table-col-resizable.directive.ts
> +    const bem = buildBem('aui-table');
从table那里导入吧

2023-12-15 09:48 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +  containerElement: Element; // 要插入参考线的容器元素
这个设计不好，在这里是input，在继承的子类里又是在ngAfterViewInit里覆盖的。而且在继承的子类里这个还是会被声明称input。

确定ResizableDirective是可以独立使用的？

2023-12-15 09:48 UTC, fengtianze commented on stories/table/basic.component.ts
> +          auiTableColResizable
加独立的story demo

2023-12-15 09:49 UTC, fengtianze commented
![CleanShot 2023-12-15 at 17 48 56@2x](https://github.com/alauda/ui/assets/16134228/b2f37515-8a77-4d3f-aa32-c2d5767150ea)
demo异常

2023-12-29 03:44 UTC, igauch commented on src/resizable/resizable.directive.ts
> + * 因为参考线是基于absolute定位的，所以需要在预期的地方加上relative（不自动加是为了避免修改业务布局而导致使用者出现意外的异常）
在table组件里加了，这个说明是针对通用指令说的

2023-12-29 03:58 UTC, igauch commented on src/resizable/resizable.directive.ts
> +    this.renderer2.listen(this.element, 'mouseover', () => {
<img width="719" alt="image" src="https://github.com/alauda/ui/assets/20862002/69d22fb3-2da2-46ce-9bea-614e6785ae88">

2023-12-29 04:06 UTC, igauch commented on src/resizable/resizable.directive.ts
> +      this.renderer2.setStyle(this.resizeHandle, 'opacity', 1);
封装显示隐藏？

2023-12-29 04:07 UTC, igauch commented on src/resizable/resizable.directive.ts
> +    const _max = this.containerElement.clientWidth - this.getOffset();
不能，这是定位用的

2023-12-29 04:08 UTC, igauch commented on src/resizable/resizable.directive.ts
> +  private handleWidth(width: string | number) {
这个处理就是也支持%，先这样吧

2023-12-29 04:41 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +      this.renderer2.setStyle(this.resizeHandle, 'opacity', 1);
对

2023-12-29 04:45 UTC, fengtianze commented on src/resizable/resizable.directive.ts
> +    return overMinWidth ? (underMaxWidth ? newWidth : maxWidth) : minWidth;
return Math.max(Math.min(maxWidth, width), minWidth)

2023-12-29 07:13 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    this.renderer2.listen(this.element, 'mouseover', () => {
首先这里是用的 Angular 的 API，不是原生 API，里面的黑盒我们不清楚，其次能从自己代码里避免的问题不要依赖外部环境。

2023-12-29 07:17 UTC, JounQin requested changes

2023-12-29 07:17 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      return (tableWidth * parseInt(width, 10)) / 100;
```suggestion
      return (tableWidth * Number.parseFloat(width, 10)) / 100;
```

下同

2023-12-29 07:17 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +    this.resizeEndEvent.subscribe(width => {
takeUntil

2023-12-29 07:17 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +      this.styleEl.innerHTML = `
用 stylesheet API ？

2024-01-02 06:23 UTC, JounQin requested changes

2024-01-02 06:23 UTC, JounQin commented on scripts/build.js
> +  const themeDest = releaseDest + '/theme';
用 path.resolve 提升 Windows 兼容性

2024-01-02 06:23 UTC, JounQin commented on scripts/build.js
> +    .pipe(gulp.dest(releaseDest + '/resizable'));
同上

2024-01-02 06:23 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +  private readonly move = (event: MouseEvent) => {
必须用箭头函数吗？

2024-01-02 06:23 UTC, JounQin commented on src/table/table-header-cell.directive.ts
> +const bem = buildBem(TABLE_PREFIX_CLASSNAME);
这个可以直接导出 tableBem 吧

2024-01-02 06:23 UTC, JounQin commented on src/table/table-scroll.directive.ts
> +const SHADOW_CLASS = `${TABLE_PREFIX_CLASSNAME}__scroll-shadow`;
用 tableBem 构造

2024-01-02 06:23 UTC, JounQin commented on src/table/table.spec.ts
> +const bem = buildBem(TABLE_PREFIX_CLASSNAME);
```suggestion
export const tableBem = buildBem(TABLE_PREFIX_CLASSNAME);
```

2024-01-03 03:25 UTC, JounQin requested changes

2024-01-03 03:25 UTC, JounQin commented on scripts/build.js
> +  const themeDest = path.resolve(releaseDest + '/theme');
```suggestion
  const themeDest = path.resolve(releaseDest, 'theme');
```

2024-01-03 03:25 UTC, JounQin commented on scripts/build.js
> +    .pipe(gulp.dest(path.resolve(releaseDest + '/resizable')));
```suggestion
    .pipe(gulp.dest(path.resolve(releaseDest, 'resizable')));
```

2024-01-03 05:27 UTC, JounQin requested changes

2024-01-03 05:27 UTC, JounQin commented on angular.json
> +            "enableProdMode": false
加个注释链接到相关 issue

2024-01-03 05:27 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +  constructor(
为啥风格不一致？一会儿 inject，一会儿 constructor

2024-01-03 05:27 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      .subscribe(callback);
```suggestion
```

感觉自己 subscribe 就行

2024-01-03 05:27 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    this.resizeHandle &&
if block

2024-01-03 05:27 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    if (!this.resizeHandle) {
```suggestion
    if (this.resizeHandle) {
      return;
```

减少嵌套

2024-01-03 05:27 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +        this.hostAttr = `resizable-${(Math.random() * 1_000_000).toFixed(0)}`;
感觉可以用 uid++ 这种？

2024-01-03 05:43 UTC, igauch commented on angular.json
> +            "enableProdMode": false
json不允许注释，加一个issue？

2024-01-03 05:44 UTC, igauch commented on src/resizable/resizable.directive.ts
> +      .subscribe(callback);
都需要sub就内部sub了，而且这就是绑定事件，没必要在外部sub

2024-01-03 05:45 UTC, igauch commented on src/table/table-col-resizable.directive.ts
> +        this.hostAttr = `resizable-${(Math.random() * 1_000_000).toFixed(0)}`;
也行，不过为了避免可能的重复。所以使用随机的方式

2024-01-03 06:45 UTC, JounQin commented on angular.json
> +            "enableProdMode": false
这个其实是 jsonc

2024-01-03 06:45 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      .subscribe(callback);
有啥区别？你不还是把 callback 穿进去吗？

2024-01-03 06:46 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +        this.hostAttr = `resizable-${(Math.random() * 1_000_000).toFixed(0)}`;
随机数才可能重复，uid 怎么可能重复

2024-01-03 06:54 UTC, igauch commented on src/table/table-col-resizable.directive.ts
> +        this.hostAttr = `resizable-${(Math.random() * 1_000_000).toFixed(0)}`;
我说的重复是指与业务的。当然，这种可能性都可以忽略

2024-01-03 06:55 UTC, igauch commented on src/resizable/resizable.directive.ts
> +      .subscribe(callback);
对啊，我没必要在每个使用的地方再sub了，callback都需要，没差别

2024-01-03 07:04 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      .subscribe(callback);
当然有差别，style 和自由度，如果你临时想加一个 operator 怎么办？

2024-01-03 07:04 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +        this.hostAttr = `resizable-${(Math.random() * 1_000_000).toFixed(0)}`;
uid 弄成全局的，不可能重复

2024-01-03 08:21 UTC, JounQin requested changes

2024-01-03 08:21 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    this.handleHasUp && this.setResizeHandleVisible(true);
if block

2024-01-03 08:21 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      `${finalWidth + this.getOffset() - this.BAR_WIDTH}px`,
有个 handlePixel 的 util

2024-01-03 08:21 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +
```suggestion
```

这里换行很奇怪

2024-01-03 08:21 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    if (width.includes('%')) {
```suggestion
    if (width.endsWith('%')) {
```

2024-01-03 08:21 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +  private readonly tableColumnDefDirective = inject(TableColumnDefDirective);
inject/constructor 同一个 PR 统一一下

2024-01-04 01:31 UTC, JounQin commented on src/resizable/resizable.directive.ts
> + * 使用此指令需要引入resizable.scss
写一下完整路径，别人可以直接复制粘贴的那种。

```js
/**
 * @example `node_modules/@alauda/ui/xxx`
 */
```

2024-01-04 04:05 UTC, JounQin commented
不要总是用 ammend + force push，每次冲突都要重新 review 完整的 PR？应该分 commit 更方便 review ，也能保留修改历史

2024-01-04 04:11 UTC, JounQin requested changes

2024-01-04 04:11 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    ).subscribe(e => {
统一一下

```suggestion
    ).subscribe(ev => {
```

2024-01-04 04:53 UTC, JounQin requested changes

2024-01-04 04:53 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      mouseUpSubscription.unsubscribe();
用 `take(1)` 就不用 unsubscribe 了，`mousemove` 的 sub 和可以和这个合并起来，`takeUtil(mouseup$)`.

2024-01-04 05:10 UTC, JounQin requested changes

2024-01-04 05:10 UTC, JounQin commented on stories/resizable/basic.component.ts
> +    this.resizable.get(idx).nativeElement.style.width = `${width}px`;
为什么 demo 里要自己设置 `style.width` 属性？不如直接文本显示出来

2024-01-04 07:20 UTC, igauch commented on stories/resizable/basic.component.ts
> +    this.resizable.get(idx).nativeElement.style.width = `${width}px`;
更直观啊

2024-01-04 07:28 UTC, JounQin commented on stories/resizable/basic.component.ts
> +    this.resizable.get(idx).nativeElement.style.width = `${width}px`;
哪里直观了，我会以为必须得自己设置 width 才能生效，直接把文本显示出来不是更直观？

2024-01-04 07:35 UTC, igauch commented on stories/resizable/basic.component.ts
> +    this.resizable.get(idx).nativeElement.style.width = `${width}px`;
这个生效是指什么？宽度变化？那就是需要设置的

2024-01-04 07:44 UTC, JounQin commented on stories/resizable/basic.component.ts
> +    this.resizable.get(idx).nativeElement.style.width = `${width}px`;
table 列宽拖动不会自动设置？？那这个 API 没封装完啊。

2024-01-04 07:49 UTC, igauch commented on stories/resizable/basic.component.ts
> +    this.resizable.get(idx).nativeElement.style.width = `${width}px`;
table列宽不需要设置，table拖拽扩展了这个抽象。
设计如此，例如table这里，并不能直接设置指令host元素的宽度。所以把这个处理交给业务处理

2024-01-04 07:50 UTC, JounQin commented on stories/resizable/basic.component.ts
> +    this.resizable.get(idx).nativeElement.style.width = `${width}px`;
这在我看来就是功能没做完

2024-01-04 10:35 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +  override readonly manualAdjustment = true;
这个为啥是 `true` 还不让改？

2024-01-04 10:49 UTC, JounQin requested changes

2024-01-04 10:49 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +        this.onMousedown(event);
不是这个意思，你这还是命令式的。。。

https://github.com/JounQin/blog/issues/419

2024-01-04 10:53 UTC, JounQin requested changes

2024-01-04 10:53 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +      if (CSSStyleSheet) {
```suggestion
      if (typeof CSSStyleSheet !== 'undefined') {
```

原来的写法在没有 CSSStyleSheet 的环境会 `ReferenceError: CSSStyleSheet is not defined`.

2024-01-04 10:54 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +      document.adoptedStyleSheets.splice(idx, 1);
```suggestion
      document.adoptedStyleSheets.splice(idx, 1);
      this.sheet = null;
```

2024-01-04 10:55 UTC, JounQin commented on src/resizable/resizable.directive.ts
> + * @example `node_modules/@alauda/ui/resizable/resizable`
```suggestion
 *
 * @example `@import 'node_modules/@alauda/ui/resizable/resizable';`
```

2024-01-04 10:55 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +  elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
```suggestion
  elementRef = inject(ElementRef<HTMLElement>);
```

2024-01-05 01:30 UTC, igauch commented on src/table/table-col-resizable.directive.ts
> +  override readonly manualAdjustment = true;
对，table组件的行为应该是内置的，统一的，不需要业务关心

2024-01-05 01:56 UTC, igauch commented on src/resizable/resizable.directive.ts
> +  elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
<img width="480" alt="image" src="https://github.com/alauda/ui/assets/20862002/9d9f2345-100a-43b6-aae1-c775a51a8b9c">

2024-01-05 02:37 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +  override readonly manualAdjustment = true;
那为啥这里是 true？

2024-01-05 02:37 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +  elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
👌

2024-01-05 02:46 UTC, igauch commented on src/table/table-col-resizable.directive.ts
> +  override readonly manualAdjustment = true;
因为基础指令的 manualAdjustment 默认是false，是自动调整宿主的宽度的。而这里对于基础指令来说是需要自己控制调整逻辑的，所以是true。但是对业务这不是应该关心的点，所以不让修改。

2024-01-05 02:49 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +  override readonly manualAdjustment = true;
👌

2024-01-05 02:59 UTC, JounQin commented on src/resizable/resizable.directive.ts
> + * @example `@import 'node_modules/@alauda/ui/resizable/resizable';`
换行。。。

2024-01-05 03:04 UTC, JounQin requested changes

2024-01-05 03:04 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    let initialWidth: number;
看起来不需要在这一层声明

2024-01-05 03:04 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    let mouseDownScreenX: number;
同上

2024-01-05 03:15 UTC, JounQin approved these changes

2024-01-05 03:15 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    class: 'aui-resizable',
是不是能直接用 attr 做 css selector，加一个 class 似乎没有必要

2024-01-05 03:18 UTC, igauch commented on src/resizable/resizable.directive.ts
> +    let initialWidth: number;
需要吧，这两个都分别在 mousedown/mousemove 有使用

2024-01-05 04:03 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    let initialWidth: number;
建议再看下 https://github.com/JounQin/blog/issues/419

2024-01-05 05:51 UTC, igauch commented on src/resizable/resizable.directive.ts
> +    let initialWidth: number;
不太理解，我需要在 mouseup 做一些事，并且依赖 mousedown 时的一些值。
是要在 mousedown 的流里再订阅一次 mouseup？

2024-01-05 07:16 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    let initialWidth: number;
<img width="520" alt="image" src="https://github.com/alauda/ui/assets/8336744/d91e746b-03ed-4d41-809c-d6e1ad1a8bdc">

这里不是一模一样吗？

2024-01-05 08:17 UTC, igauch commented on src/resizable/resizable.directive.ts
> +    let initialWidth: number;
这是 mousedown => mousemove，但我还要在 mouseup 中使用

2024-01-08 01:45 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +            fromEvent<MouseEvent>(document, 'mousemove').pipe(
mousemove$ 往上提

2024-01-08 01:46 UTC, JounQin requested changes

2024-01-08 01:46 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +                fromEvent<MouseEvent>(document, 'mouseup').pipe(
mouseup$ 往上提

2024-01-08 01:47 UTC, JounQin commented on stories/table/basic.component.ts
> +          auiTableColResizable
加一个独立使用的 table 的例子

2024-01-08 01:48 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +  host: {
看看能不能不要

2024-01-08 01:50 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +  renderer2 = inject(Renderer2);
重新组织一下 fields 顺序，public 优先，private 放后面

2024-01-08 01:50 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +  private readonly BAR_WIDTH = 2;
常量？不需要放 field，提到组件外

2024-01-08 01:52 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      this.element.clientWidth + this.getOffset() - this.BAR_WIDTH + 'px',
handelPixel

2024-01-08 01:53 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    const _max = this.containerElement.clientWidth + this.getOffset();
```suggestion
    const max = this.containerElement.clientWidth + this.getOffset();
```

看起来没有冲突啊

2024-01-08 01:56 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +      document.adoptedStyleSheets.splice(idx, 1);
看了下它就是个纯数组，用 filter 赋值就行

2024-01-08 01:57 UTC, JounQin commented on src/table/table-scroll.directive.ts
> +  @HostBinding('class')
能用 host 处理吗？还是因为有 runtime 的代码只能用 HostBinding？

2024-01-08 01:58 UTC, JounQin commented on src/table/table.component.ts
> +  className = tableBem.block();
同上

2024-01-08 01:59 UTC, JounQin commented
大哥辛苦了，咱们很接近目标了。

2024-01-08 02:17 UTC, igauch commented on src/resizable/resizable.directive.ts
> +            fromEvent<MouseEvent>(document, 'mousemove').pipe(
为什么要往上提呀？

2024-01-08 02:17 UTC, igauch commented on src/table/table-scroll.directive.ts
> +  @HostBinding('class')
因为有 runtime 的代码只能用 HostBinding

2024-01-08 02:18 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +            fromEvent<MouseEvent>(document, 'mousemove').pipe(
因为不需要每次都执行一遍。。。

2024-01-08 02:31 UTC, igauch commented on src/resizable/resizable.directive.ts
> +            fromEvent<MouseEvent>(document, 'mousemove').pipe(
那就是提到组件的 field 级别，我还停留在这个函数的顶级这里

2024-01-08 02:35 UTC, igauch commented on src/resizable/resizable.directive.ts
> +            fromEvent<MouseEvent>(document, 'mousemove').pipe(
不对，这个函数也是只执行一次的，应该就在这个函数里就行😅

2024-01-08 02:52 UTC, yinshuxun commented
尝试了下本地 demo，有几个问题
 1 、刚才尝试了下拖动表格之外这个交互是允许的么
<img width="1176" alt="image" src="https://github.com/alauda/ui/assets/18656086/c71eb649-894e-4538-9ec4-640a112ec191">
2 、快速拖动到 iframe 之外会丢失 mouseup 事件，感觉得考虑一下

2024-01-08 03:51 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +      .subscribe(event => event.stopPropagation());
下面 `mousedown` 已经阻止冒泡了，确实这个还需要吗？

2024-01-08 03:54 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    const maxWidth = this.handleWidth(this.maxWidth || _max);
```suggestion
    const maxWidth = this.handleWidth(this.maxWidth || this.containerElement.clientWidth + this.getOffset());
```

2024-01-08 04:11 UTC, JounQin commented on src/table/table-col-resizable.directive.ts
> +import { AfterViewInit, Directive, inject, Input } from '@angular/core';
我问了一下其他同事的反馈

```diff
diff --git a/src/resizable/resizable.directive.ts b/src/resizable/resizable.directive.ts
index ec35bee..758e804 100644
--- a/src/resizable/resizable.directive.ts
+++ b/src/resizable/resizable.directive.ts
@@ -52,109 +52,110 @@ export class ResizableDirective implements AfterViewInit, OnDestroy {
   @Output()
   resizeEnd = new EventEmitter<number>();
 
-  get element() {
-    return this.elementRef.nativeElement;
-  }
-
-  get clientWidth() {
-    return this.element.clientWidth;
-  }
-
-  get resizeElement() {
-    return this.createResizeElement();
-  }
-
-  renderer2 = inject(Renderer2);
   private readonly elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
+  renderer2 = inject(Renderer2);
   private readonly containerDirective = inject(ContainerForResizableDirective, {
     optional: true,
   });
 
   private readonly BAR_WIDTH = 2;
+
+  private readonly element = this.elementRef.nativeElement;
   containerElement = this.containerDirective?.el.nativeElement || this.element;
 
   destroy$$ = new Subject<void>();
-  click$ = fromEvent<Event>(this.resizeElement, 'click');
-  mousedown$ = fromEvent<MouseEvent>(this.resizeElement, 'mousedown');
-  mousemove$ = fromEvent<MouseEvent>(document, 'mousemove');
-  mouseup$ = fromEvent<MouseEvent>(document, 'mouseup');
 
   ngAfterViewInit() {
-    this.click$
+    const resizeHandle = this.createResizeHandle();
+
+    fromEvent<Event>(resizeHandle, 'click')
       .pipe(takeUntil(this.destroy$$))
       .subscribe(event => event.stopPropagation());
 
-    this.mousedown$
+    this.bindResizable(resizeHandle);
+  }
+
+  ngOnDestroy() {
+    this.destroy$$.next();
+    this.destroy$$.complete();
+  }
+
+  private bindResizable(resizeHandle: HTMLElement) {
+    fromEvent<MouseEvent>(resizeHandle, 'mousedown')
       .pipe(
-        tap(event => {
+        map(event => {
           event.preventDefault();
           event.stopPropagation();
 
-          this.resizeStart.emit(this.clientWidth);
+          const initialWidth = this.element.clientWidth;
+          this.resizeStart.emit(initialWidth);
 
           // 避免两条线不对齐
-          this.renderer2.setStyle(this.resizeElement, 'visibility', 'hidden');
+          this.renderer2.setStyle(resizeHandle, 'visibility', 'hidden');
+
+          return {
+            resizeBar: this.createResizeBar(),
+            resizeOverlay: this.createResizeOverlay(),
+            initialWidth,
+            mouseDownScreenX: event.clientX,
+          };
         }),
-        switchMap(downEvent => {
-          const resizeBar = this.createResizeBar();
-          const resizeOverlay = this.createResizeOverlay();
-          const mouseDownScreenX = downEvent.clientX;
-
-          return this.mousemove$.pipe(
-            map(event => {
-              const movementX = event.clientX - mouseDownScreenX;
-              const newWidth = this.clientWidth + movementX;
-              const width = this.getFinalWidth(newWidth);
-              this.renderer2.setStyle(
-                resizeBar,
-                'left',
-                handlePixel(width + this.getOffset() - this.BAR_WIDTH),
-              );
-              return width;
-            }),
-            takeUntil(
-              this.mouseup$.pipe(
-                tap(event => {
-                  this.renderer2.removeStyle(this.resizeElement, 'visibility');
-
-                  this.renderer2.removeChild(
-                    this.containerElement,
-                    resizeOverlay,
-                  );
-                  this.renderer2.removeChild(this.containerElement, resizeBar);
-
-                  const movementX = event.clientX - mouseDownScreenX;
-                  const newWidth = this.clientWidth + movementX;
-                  const width = this.getFinalWidth(newWidth);
-                  if (!this.manualAdjustment) {
-                    this.renderer2.setStyle(
-                      this.element,
-                      'width',
-                      handlePixel(width),
+        switchMap(
+          ({ resizeBar, resizeOverlay, initialWidth, mouseDownScreenX }) =>
+            fromEvent<MouseEvent>(document, 'mousemove').pipe(
+              map(event => {
+                const movementX = event.clientX - mouseDownScreenX;
+                const newWidth = initialWidth + movementX;
+                const width = this.getFinalWidth(newWidth);
+                this.renderer2.setStyle(
+                  resizeBar,
+                  'left',
+                  handlePixel(width + this.getOffset() - this.BAR_WIDTH),
+                );
+                return width;
+              }),
+              takeUntil(
+                fromEvent<MouseEvent>(document, 'mouseup').pipe(
+                  tap(event => {
+                    this.renderer2.removeStyle(resizeHandle, 'visibility');
+
+                    this.renderer2.removeChild(
+                      this.containerElement,
+                      resizeOverlay,
                     );
-                  }
-                  this.resizeEnd.emit(width);
-                }),
+                    this.renderer2.removeChild(
+                      this.containerElement,
+                      resizeBar,
+                    );
+
+                    const movementX = event.clientX - mouseDownScreenX;
+                    const newWidth = initialWidth + movementX;
+                    const width = this.getFinalWidth(newWidth);
+                    if (!this.manualAdjustment) {
+                      this.renderer2.setStyle(
+                        this.element,
+                        'width',
+                        handlePixel(width),
+                      );
+                    }
+                    this.resizeEnd.emit(width);
+                  }),
+                ),
               ),
             ),
-          );
-        }),
+        ),
+        takeUntil(this.destroy$$),
       )
       .subscribe(width => {
         this.resizing.emit(width);
       });
   }
 
-  ngOnDestroy() {
-    this.destroy$$.next();
-    this.destroy$$.complete();
-  }
-
-  private createResizeElement() {
-    const element = this.renderer2.createElement('div');
-    this.renderer2.addClass(element, 'resize-handle');
-    this.renderer2.appendChild(this.element, element);
-    return element;
+  private createResizeHandle() {
+    const resizeHandle = this.renderer2.createElement('div');
+    this.renderer2.addClass(resizeHandle, 'resize-handle');
+    this.renderer2.appendChild(this.element, resizeHandle);
+    return resizeHandle;
   }
 
   private createResizeOverlay() {
@@ -173,16 +174,14 @@ export class ResizableDirective implements AfterViewInit, OnDestroy {
       this.element.clientWidth + this.getOffset() - this.BAR_WIDTH + 'px',
     );
     this.renderer2.appendChild(this.containerElement, resizeBar);
-
     return resizeBar;
   }
 
   private getFinalWidth(newWidth: number): number {
     // 不能超出边界
-    const max = this.containerElement.clientWidth + this.getOffset();
+    const _max = this.containerElement.clientWidth + this.getOffset();
     const minWidth = this.handleWidth(this.minWidth || this.getOffset());
-    const maxWidth = this.handleWidth(this.maxWidth || max);
-
+    const maxWidth = this.handleWidth(this.maxWidth || _max);
     return Math.max(Math.min(maxWidth, newWidth), minWidth);
   }
 
@@ -197,16 +196,13 @@ export class ResizableDirective implements AfterViewInit, OnDestroy {
     if (typeof width === 'number') {
       return width;
     }
-
     if (!width) {
       return;
     }
-
     if (width.endsWith('%')) {
       const tableWidth = this.containerElement.clientWidth;
       return (tableWidth * Number.parseFloat(width)) / 100;
     }
-
     return Number.parseFloat(width.replace(/\D+/, ''));
   }
 }
```

2024-01-08 04:17 UTC, JounQin commented on stories/resizable/basic.stories.ts
> +export const Basic: Story = {
```suggestion
export const Basic: StoryObj<BasicComponent> = {
```

2024-01-13 09:14 UTC, MrCoder commented on src/resizable/resizable.directive.ts
> +    const maxWidth = this.handleWidth(this.maxWidth || _max);
为什么要inline这个变量啊？

2024-01-13 09:17 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +    const maxWidth = this.handleWidth(this.maxWidth || _max);
因为它可能不需要执行

2024-01-13 12:28 UTC, JounQin commented on src/resizable/resizable.directive.ts
> +            fromEvent<MouseEvent>(document, 'mousemove').pipe(
虽然只执行一次，但是提到外面更清晰易读。

2024-01-17 16:27 UTC, JounQin commented on src/table/table-column-resizable.directive.ts
> +                  resizeMarkLine.updateOffset(
为啥在 map 做副作用？

2024-01-18 02:50 UTC, fengtianze commented on src/table/table-column-resizable.directive.ts
> +                  resizeMarkLine.updateOffset(
这是 map to 函数

2024-01-18 03:02 UTC, JounQin commented on src/utils/styles-render.ts
> +      document.adoptedStyleSheets.splice(i, 1);
这个提过，用 filter 吧，i _万一_ 是 -1 怎么办？

2024-01-18 03:03 UTC, JounQin commented on src/table/table-column-resizable.directive.ts
> +      return parseInt(width.slice(0, -2));
```suggestion
      return Number.parseFloat(width.slice(0, -2));
```

怎么感觉被恢复成最开始的代码了？所有 review 后的变更都没了。。。

2024-01-18 03:03 UTC, JounQin commented on src/table/table-column-resizable.directive.ts
> +    return parseInt(width);
```suggestion
    return Number.parseFloat(width);
```

2024-01-18 03:05 UTC, JounQin commented on src/table/table-column-resizable.directive.ts
> +          const mouseUp$ = fromEvent<MouseEvent>(document, 'mouseup').pipe(
可以提到 `bindResizable` 函数内这一层吧

2024-01-18 03:06 UTC, JounQin commented on src/table/table-column-resizable.directive.ts
> +        exec();
👍

2024-01-18 03:07 UTC, JounQin commented on src/table/table-column-resizable.directive.ts
> +          const mouseMove$ = fromEvent<MouseEvent>(document, 'mousemove').pipe(
同上，感觉可以往上提

2024-01-18 03:07 UTC, JounQin commented on src/table/table-column-resizable.directive.ts
> +          offset - markLineWidth + 'px',
handlePixel

2024-01-18 03:33 UTC, merged