feat: select support readonly
alauda/ui pull request #540
Opened 2024-01-02 05:56 UTC by igauch

close #539

2024-01-02 06:01 UTC, fengtianze commented on src/select/select.component.scss
> +  &__label-container.aui-input[readonly] {
为什么跟disabled和inaction设置input样式的选择器不一样？

2024-01-02 06:04 UTC, fengtianze commented
![CleanShot 2024-01-02 at 14 03 09@2x](https://github.com/alauda/ui/assets/16134228/c74047a2-8606-4f47-ae99-dec11ee1cf6c)
修复无效

2024-01-02 06:31 UTC, igauch commented
> ![CleanShot 2024-01-02 at 14 03 09@2x](https://private-user-images.githubusercontent.com/16134228/293634401-c74047a2-8606-4f47-ae99-dec11ee1cf6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzczMzYsIm5iZiI6MTcwNDE3NzAzNiwicGF0aCI6Ii8xNjEzNDIyOC8yOTM2MzQ0MDEtYzc0MDQ3YTItODYwNi00ZjQ3LWFlOTktZGVjMTFlZTFjZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA2MzAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNmM0ZmNiNzg0OTdjMzY0MjliMjEwMjhjZDcxMTBmNzhlMTU1NWVkNWU2MTFmZDc1ZWQwNDVmZGViZWM2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7uKCOck3Q_Ckg2JiqPoHzsuGmA17FQz8gfL1czTVyGY) 修复无效

done

2024-01-02 06:34 UTC, JounQin requested changes

2024-01-02 06:34 UTC, JounQin commented on .changeset/beige-bananas-grin.md
> +'@alauda/ui': patch
```suggestion
'@alauda/ui': minor
```

2024-01-02 06:34 UTC, JounQin commented on src/form/common-form.ts
> +    this._disabled = this._readonly === true ? true : coerceAttrBoolean(val);
```suggestion
    this._disabled = this._readonly || coerceAttrBoolean(val);
```

2024-01-02 06:34 UTC, JounQin commented on src/input/input.component.scss
> +  &[readonly] {
和 disabled 一样的样式可以合并一个 selector

2024-01-15 04:41 UTC, JounQin commented on src/select/select.component.html
> +      [attr.readonly]="readonly ? true : null"
```suggestion
      [attr.readonly]="readonly ? true : ''"
```

记得 `null` 有问题，试一下

2024-01-15 04:41 UTC, JounQin commented on stories/select/basic.component.ts
> +   */
```suggestion
```

2024-01-15 09:04 UTC, igauch commented on src/select/select.component.html
> +      [attr.readonly]="readonly ? true : null"
如果改成空 readonly 即便是 false， readonly 属性也还是存在，只是没有值了，这不是期望的，还是期望没有 readonly 属性。null 可以。语法：https://angular.cn/guide/attribute-binding#syntax

不知道你说的问题是指什么

2024-01-15 15:17 UTC, JounQin commented on src/select/select.component.html
> +      [attr.readonly]="readonly ? true : null"
https://github.com/angular/angular/issues/24503#issuecomment-397238727

2024-01-15 15:19 UTC, JounQin approved these changes

2024-01-16 03:05 UTC, fengtianze approved these changes

2024-01-16 03:06 UTC, merged